server:
  port: 8080
  error:
    include-exception: true # lets user see the exception canonical on 400 status code (invalid MorseDto)
    include-binding-errors: always # lets the user see the cause of the constraint validation error.

morse:
  alphabet:
    "A": ".-"
    "B": "-..."
    "C": "-.-."
    "D": "-.."
    "E": "."
    "F": "..-."
    "G": "--."
    "H": "...."
    "I": ".."
    "J": ".---"
    "K": "-.-"
    "L": ".-.."
    "M": "--"
    "N": "-."
    "O": "---"
    "P": ".--."
    "Q": "--.-"
    "R": ".-."
    "S": "..."
    "T": "-"
    "U": "..-"
    "V": "...-"
    "X": "-..-"
    "Y": "-.--"
    "Z": "--.."
    "0": "-----"
    "1": ".----"
    "2": "..---"
    "3": "...--"
    "4": "....-"
    "5": "....."
    "6": "-...."
    "7": "--..."
    "8": "---.."
    "9": "----."
    ".": ".-.-.-"

spring:
  cache: # for caching
    caffeine: # for ttl
      spec: expireAfterWrite=5m
    cache-names: morseCache